name: Grafico Node.js app

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: cd server && npm ci
    - name: Initialize tests
      run: cd server && npm test
